#:schema ./schema/mise.json
min_version = "2024.1.1"

[env]
_.path = ["./target/debug", "./node_modules/.bin"]

[tools]
"actionlint" = "1.7.10"
age = "1.3.1"
bun = "1.3.8"
cargo-binstall = "1.17.4"
"cargo:cargo-edit" = "0.13.8"
"cargo:cargo-insta" = "1.46.1"
"cargo:cargo-release" = "0.25.22"
"cargo:git-cliff" = "2.12.0"
"cargo:toml-cli" = "0.2.3"
"cargo:usage-cli" = { version = "2.16.0", os = ["linux", "macos"] }
gh = "2.86.0"
hk = "1.34.0"
jq = "1.8.1"
fd = "10.3.0"
"npm:markdownlint-cli" = "0.47.0"
"npm:prettier" = "3.8.1"
"npm:ajv-cli" = "5.0.0"
pkl = "0.30.2"
pre-commit = "4.5.1"
#"python" = { version = "3.12", virtualenv = "{{env.HOME}}/.cache/venv" }
"ripgrep" = "15.1.0"
"shellcheck" = "0.11.0"
"shfmt" = "3.12.0"
taplo = "0.10.0"
wait-for-gh-rate-limit = "1.1.1"
sops = "3.11.0"
node = "24.13.0"

[task_config]
includes = ["tasks.toml", "xtasks"]
